package com.assist.platform.model;

import java.util.List;

/**
 * Catalog generated by MyEclipse Persistence Tools
 */

public class Catalog implements java.io.Serializable {

	// Fields

	private Integer catalogid;
	private String catalogname;
	private String cataloginfo;
	private Integer parentid;
	private List<Message> messages;

	// Constructors

	/** default constructor */
	public Catalog() {
	}
	
	public Catalog(Integer catalogid) {
		this.catalogid = catalogid;
	}

	/** full constructor */
	public Catalog(Integer catalogid, String catalogname, String cataloginfo,
			Integer parentid, List<Message> messages) {
		this.catalogid = catalogid;
		this.catalogname = catalogname;
		this.cataloginfo = cataloginfo;
		this.parentid = parentid;
		this.messages = messages;
	}

	// Property accessors
	public Integer getCatalogid() {
		return this.catalogid;
	}

	public void setCatalogid(Integer catalogid) {
		this.catalogid = catalogid;
	}

	public String getCatalogname() {
		return this.catalogname;
	}

	public void setCatalogname(String catalogname) {
		this.catalogname = catalogname;
	}

	public String getCataloginfo() {
		return this.cataloginfo;
	}

	public void setCataloginfo(String cataloginfo) {
		this.cataloginfo = cataloginfo;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public List<Message> getMessages() {
		return messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

}