package com.assist.platform.model;

/**
 * Favorite generated by MyEclipse Persistence Tools
 */

public class Favorite implements java.io.Serializable {

	// Fields

	private Integer favoriteid;
	private Message message;
	private User user;

	// Constructors

	/** default constructor */
	public Favorite() {
	}

	/** full constructor */
	public Favorite(Message message, User user) {
		this.message = message;
		this.user = user;
	}

	// Property accessors
	public Integer getFavoriteid() {
		return favoriteid;
	}

	public void setFavoriteid(Integer favoriteid) {
		this.favoriteid = favoriteid;
	}

	public Message getMessage() {
		return message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}