package com.assist.platform.model;

import java.util.List;

/**
 * Func generated by MyEclipse Persistence Tools
 */

public class Func implements java.io.Serializable {

	// Fields

	private Integer funcid;
	private Module module;
	private String funcname;
	private String path;
	private List<Path> paths;
	private List<Role> roles;

	// Constructors

	/** default constructor */
	public Func() {
	}

	/** full constructor */
	public Func(Integer funcid, Module module, String funcname, String path,
			List<Path> paths, List<Role> roles) {
		this.funcid = funcid;
		this.module = module;
		this.funcname = funcname;
		this.path = path;
		this.paths = paths;
		this.roles = roles;
	}

	// Property accessors
	public Integer getFuncid() {
		return this.funcid;
	}

	public void setFuncid(Integer funcid) {
		this.funcid = funcid;
	}

	public Module getAdpModule() {
		return this.module;
	}

	public void setAdpModule(Module module) {
		this.module = module;
	}

	public String getFuncname() {
		return this.funcname;
	}

	public void setFuncname(String funcname) {
		this.funcname = funcname;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Module getModule() {
		return module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public List<Path> getPaths() {
		return paths;
	}

	public void setPaths(List<Path> paths) {
		this.paths = paths;
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

}