package com.assist.platform.model;

import java.util.Date;
import java.util.List;

/**
 * Message generated by MyEclipse Persistence Tools
 */

public class Message implements java.io.Serializable {

	// Fields

	private Integer messageid;
	private User user;
	private Catalog catalog;
	private String title;
	private String content;
	private Integer status;    // 状态 1 未回复 2 部分回复 3 已回复 4 已忽略
	private Integer type;     // 类别 1 提问 2 建议
	private Date createtime;
	private Date modifytime;
	private Date replytime;
	private Integer istop;	   // 置顶,出现在首页 0 未被置顶 1已被置顶 
	private Integer checked;   // 是否已读 0 未读 1已读
	private Integer isdel;     // 是否被删除 0 未删 1已删
	private Integer recommend; // 是否被推荐出现在常见问题/精彩建议 0 未被推荐 1已被推荐
	private List<Reply> replys;
	private List<Favorite> favorites;

	// Constructors

	/** default constructor */
	public Message() {
	}

	/** full constructor */
	public Message(Integer messageid, User user, Catalog catalog, String title,
			String content, Integer status, Integer type, Date createtime,
			Date modifytime, Date replytime, Integer istop, Integer checked,
			Integer isdel, Integer recommend, List<Reply> replys,
			List<Favorite> favorites) {
		this.messageid = messageid;
		this.user = user;
		this.catalog = catalog;
		this.title = title;
		this.content = content;
		this.status = status;
		this.type = type;
		this.createtime = createtime;
		this.modifytime = modifytime;
		this.replytime = replytime;
		this.istop = istop;
		this.checked = checked;
		this.isdel = isdel;
		this.recommend = recommend;
		this.replys = replys;
		this.favorites = favorites;
	}

	// Property accessors

	public Integer getMessageid() {
		return messageid;
	}

	public void setMessageid(Integer messageid) {
		this.messageid = messageid;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Catalog getCatalog() {
		return catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getModifytime() {
		return modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	public Date getReplytime() {
		return replytime;
	}

	public void setReplytime(Date replytime) {
		this.replytime = replytime;
	}

	public Integer getIstop() {
		return istop;
	}

	public void setIstop(Integer istop) {
		this.istop = istop;
	}

	public Integer getChecked() {
		return checked;
	}

	public void setChecked(Integer checked) {
		this.checked = checked;
	}

	public Integer getIsdel() {
		return isdel;
	}

	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	public Integer getRecommend() {
		return recommend;
	}

	public void setRecommend(Integer recommend) {
		this.recommend = recommend;
	}

	public List<Favorite> getFavorites() {
		return favorites;
	}

	public void setFavorites(List<Favorite> favorites) {
		this.favorites = favorites;
	}

	public List<Reply> getReplys() {
		return replys;
	}

	public void setReplys(List<Reply> replys) {
		this.replys = replys;
	}

}