package com.assist.platform.model;

/**
 * Path generated by MyEclipse Persistence Tools
 */

public class Path implements java.io.Serializable {

	// Fields

	private Integer pathid;
	private String pathname;
	private String pathurl;
	private String actionname;
	private String pathinfo;
	private String pathsign;
	private String resultname;
	private Integer funcid;

	// Constructors

	/** default constructor */
	public Path() {
	}

	/** full constructor */
	public Path(String pathname, String pathurl,
			String actionname, String pathinfo, String pathsign,
			String resultname,Integer funcid) {
		this.funcid = funcid;
		this.pathname = pathname;
		this.pathurl = pathurl;
		this.actionname = actionname;
		this.pathinfo = pathinfo;
		this.pathsign = pathsign;
		this.resultname = resultname;
	}

	// Property accessors

	public Integer getPathid() {
		return this.pathid;
	}

	public void setPathid(Integer pathid) {
		this.pathid = pathid;
	}

	public Integer getFuncid() {
		return funcid;
	}

	public void setFuncid(Integer funcid) {
		this.funcid = funcid;
	}

	public String getPathname() {
		return this.pathname;
	}

	public void setPathname(String pathname) {
		this.pathname = pathname;
	}

	public String getPathurl() {
		return this.pathurl;
	}

	public void setPathurl(String pathurl) {
		this.pathurl = pathurl;
	}

	public String getActionname() {
		return this.actionname;
	}

	public void setActionname(String actionname) {
		this.actionname = actionname;
	}

	public String getPathinfo() {
		return this.pathinfo;
	}

	public void setPathinfo(String pathinfo) {
		this.pathinfo = pathinfo;
	}

	public String getPathsign() {
		return this.pathsign;
	}

	public void setPathsign(String pathsign) {
		this.pathsign = pathsign;
	}

	public String getResultname() {
		return this.resultname;
	}

	public void setResultname(String resultname) {
		this.resultname = resultname;
	}

}