package com.assist.platform.model;

import java.util.Date;
import java.util.List;

/**
 * Reply generated by MyEclipse Persistence Tools
 */

public class Reply implements java.io.Serializable {

	// Fields

	private Integer replyid;
	private User user;
	private String title;
	private String content;
	private Date replytime;
	private Message message;

	// Constructors

	/** default constructor */
	public Reply() {
	}

	/** full constructor */
	public Reply(Integer replyid, User user, String title, String content,
			Date replytime, Message message) {
		this.replyid = replyid;
		this.user = user;
		this.title = title;
		this.content = content;
		this.replytime = replytime;
		this.message = message;
	}

	// Property accessors

	public Integer getReplyid() {
		return replyid;
	}

	public void setReplyid(Integer replyid) {
		this.replyid = replyid;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getReplytime() {
		return replytime;
	}

	public void setReplytime(Date replytime) {
		this.replytime = replytime;
	}

	public Message getMessage() {
		return message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

}