package com.assist.platform.model;

/**
 * RoleFunc generated by MyEclipse Persistence Tools
 */

public class RoleFunc implements java.io.Serializable {

	// Fields

	private Integer id;
	private Role role;
	private Func func;

	// Constructors

	/** default constructor */
	public RoleFunc() {
	}

	/** full constructor */
	public RoleFunc(Integer id, Role role, Func func) {
		this.id = id;
		this.role = role;
		this.func = func;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Func getFunc() {
		return func;
	}

	public void setFunc(Func func) {
		this.func = func;
	}

}