package com.assist.platform.model;

import java.util.Date;
import java.util.List;

/**
 * Role generated by MyEclipse Persistence Tools
 */

public class Role implements java.io.Serializable {

	// Fields

	private Integer roleid;
	private String rolename;
	private Date createtime;
	private String creator;
	private Integer funcid;
	private Integer groupid;
	private List<User> users;
	private List<Func> funcs;

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** full constructor */
	public Role(Integer roleid, String rolename, Date createtime,
			String creator, Integer funcid, Integer groupid, List<User> users,
			List<Func> funcs) {
		super();
		this.roleid = roleid;
		this.rolename = rolename;
		this.createtime = createtime;
		this.creator = creator;
		this.funcid = funcid;
		this.groupid = groupid;
		this.users = users;
		this.funcs = funcs;
	}

	// Property accessors

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Integer getFuncid() {
		return this.funcid;
	}

	public void setFuncid(Integer funcid) {
		this.funcid = funcid;
	}

	public Integer getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	public List<Func> getFuncs() {
		return funcs;
	}

	public void setFuncs(List<Func> funcs) {
		this.funcs = funcs;
	}

}