package com.assist.platform.model;

import java.util.Date;
import java.util.List;

/**
 * User generated by MyEclipse Persistence Tools
 */

public class User implements java.io.Serializable {

	// Fields

	private Integer userid;
	private Group group;
	private String loginname;
	private String username;
	private String password;
	private String email;
	private String tel;
	private Date createtime;
	private String score;
	private Integer isadmin; // 0 普通用户 1 匿民用户 99 管理员 
	private Integer isdel;
	private UserInfo userinfo;
	private UserRank userrank;
	private List<Role> roles;
	private List<Favorite> favorites;
	private List<Reply> replies;
	private List<Message> messages;
	private List<Log> logs;

	// Constructors

	/** default constructor */
	public User() {
	}
	
	public User(Integer userid) {
		this.userid = userid;
	}

	/** full constructor */
	public User(Integer userid, Group group, String loginname, String username,
			String password, String email, String tel, Date createtime,
			String score, Integer isadmin, Integer isdel, UserInfo userinfo,
			UserRank userrank, List<Role> roles, List<Favorite> favorites,
			List<Reply> replies, List<Message> messages, List<Log> logs) {
		this.userid = userid;
		this.group = group;
		this.loginname = loginname;
		this.username = username;
		this.password = password;
		this.email = email;
		this.tel = tel;
		this.createtime = createtime;
		this.score = score;
		this.isadmin = isadmin;
		this.isdel = isdel;
		this.userinfo = userinfo;
		this.userrank = userrank;
		this.roles = roles;
		this.favorites = favorites;
		this.replies = replies;
		this.messages = messages;
		this.logs = logs;
	}

	// Property accessors
	
	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Group getGroup() {
		return group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getScore() {
		return score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public Integer getIsadmin() {
		return isadmin;
	}

	public void setIsadmin(Integer isadmin) {
		this.isadmin = isadmin;
	}

	public Integer getIsdel() {
		return isdel;
	}

	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}

	public UserRank getUserrank() {
		return userrank;
	}

	public void setUserrank(UserRank userrank) {
		this.userrank = userrank;
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public List<Favorite> getFavorites() {
		return favorites;
	}

	public void setFavorites(List<Favorite> favorites) {
		this.favorites = favorites;
	}

	public List<Reply> getReplies() {
		return replies;
	}

	public void setReplies(List<Reply> replies) {
		this.replies = replies;
	}

	public List<Message> getMessages() {
		return messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

	public List<Log> getLogs() {
		return logs;
	}

	public void setLogs(List<Log> logs) {
		this.logs = logs;
	}
	
}